import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import QueryProvider from '@/lib/query-provider'

const urbanist = Urbanist({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
